### ISSUE TITLE
navbar toggle

### ISSUE THREAD

**Issue by dyar74** [MacGyer/yii2-materializecss#27]
I have some problem. In default view layout I have mobile toggle button under logo text. But at mobile it work good.
![default](https://cloud.githubusercontent.com/assets/1939318/25617988/a295418a-2f4d-11e7-9cfe-a63b55d9c5fb.png)
![default](https://cloud.githubusercontent.com/assets/1939318/25618008/ba63f310-2f4d-11e7-95a1-f520953048cc.png)

**Comment by MacGyer** [comment]
Hi @dyar74,

this is expected behavior as the widget is not making assumptions about the usage of mobile nav and/or its styling.

Just provide according settings for the SideNav toggle button:
https://github.com/MacGyer/yii2-materializecss/blob/master/src/widgets/Nav.php#L130
https://github.com/MacGyer/yii2-materializecss/blob/master/src/widgets/SideNav.php#L70

Cheers

**Comment by dyar74** [comment]
problem not in mobile version, in base layout render mobile toggle button

**Comment by MacGyer** [comment]
I know. This I did not say.
You want the SideNav toggle button to only show in small screen sizes (mobile)?!

So add the according options (e.g. CSS class) to `Nav::$sideNavToggleButtonOptions`.

See official docs: http://materializecss.com/helpers.html#hiding
